/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Packages;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author fandikhusnu
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        txtNIS = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        lahir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(51, 255, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 684, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 330, 30);
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(670, 30, 120, 30);
        jPanel1.add(labeljam);
        labeljam.setBounds(830, 30, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 80);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tanggal lahir");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 180, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NIS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 0, 62, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kelas");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 310, 107, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 370, 107, 34);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 430, 107, 34);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 240, 107, 34);

        buttonGroup1.add(rdLaki);
        rdLaki.setLabel("Laki-laki");
        rdLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLakiActionPerformed(evt);
            }
        });
        jPanel2.add(rdLaki);
        rdLaki.setBounds(20, 270, 90, 30);

        buttonGroup1.add(rdPerempuan);
        rdPerempuan.setLabel("Perempuan");
        jPanel2.add(rdPerempuan);
        rdPerempuan.setBounds(140, 270, 100, 30);
        jPanel2.add(txtNIS);
        txtNIS.setBounds(20, 30, 160, 29);
        jPanel2.add(txtNama);
        txtNama.setBounds(20, 90, 160, 30);

        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        jPanel2.add(txtKelas);
        txtKelas.setBounds(20, 340, 160, 31);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(20, 400, 160, 32);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 460, 220, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nama");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 60, 62, 34);
        jPanel2.add(lahir);
        lahir.setBounds(20, 150, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tempat lahir");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 120, 160, 40);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(20, 210, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 120, 260, 580);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("ISIAN DATA SISWA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(21, 0, 195, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 90, 260, 30);

        jPanel5.setBackground(new java.awt.Color(153, 255, 102));
        jPanel5.setLayout(null);

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setForeground(new java.awt.Color(153, 153, 0));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(20, 10, 90, 30);

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.setForeground(new java.awt.Color(153, 153, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(170, 10, 100, 30);

        jButton4.setBackground(new java.awt.Color(51, 255, 204));
        jButton4.setForeground(new java.awt.Color(153, 153, 0));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(330, 10, 100, 30);

        jButton5.setBackground(new java.awt.Color(51, 255, 204));
        jButton5.setForeground(new java.awt.Color(153, 153, 0));
        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(490, 10, 100, 30);

        jButton6.setBackground(new java.awt.Color(51, 255, 204));
        jButton6.setForeground(new java.awt.Color(153, 153, 0));
        jButton6.setText("EDIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(640, 10, 80, 30);

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(770, 10, 80, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(280, 90, 880, 50);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(null);

        tbData1.setBackground(new java.awt.Color(0, 204, 204));
        tbData1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        tbData1.setForeground(new java.awt.Color(0, 153, 153));
        tbData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Tempat lahir", "Tanggal lahir", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbData1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData1);
        if (tbData1.getColumnModel().getColumnCount() > 0) {
            tbData1.getColumnModel().getColumn(0).setResizable(false);
            tbData1.getColumnModel().getColumn(1).setResizable(false);
            tbData1.getColumnModel().getColumn(2).setResizable(false);
            tbData1.getColumnModel().getColumn(3).setResizable(false);
            tbData1.getColumnModel().getColumn(4).setResizable(false);
            tbData1.getColumnModel().getColumn(5).setResizable(false);
            tbData1.getColumnModel().getColumn(6).setResizable(false);
            tbData1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 860, 530);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 150, 880, 550);

        jPanel6.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(-200, -40, 1380, 770);

        setSize(new java.awt.Dimension(1175, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLakiActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
            String tanggal = dateFormat.format(jDateChooser1.getDate());
            String JK = "";
            if(rdLaki.isSelected())
            {
            }else {JK = "L";}
            if(rdPerempuan.isSelected())
                JK = "P";
            
            if(txtNIS.getText().equals("")||txtNama.getText().equals("")|| JK.equals("")||
                    txtKelas.getText().equals("")||txtEmail.getText().equals("")||
                    txtAlamat.getText().equals("")||lahir.getText().equals("")||tanggal.equals(""))
            {
                JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",
                        JOptionPane.WARNING_MESSAGE);
            }else
            {
                String SQL = "INSERT INTO t_siswa VALUES ('"+txtNIS.getText()+"','"+txtNama.getText()
                        +"','"
                        +JK+"','"+txtKelas.getText()+"','"+txtEmail.getText()
                        +"','"+txtAlamat.getText()+"','"+lahir.getText()+"','"+tanggal+"')";
                int status = KoneksiDB.execute(SQL);
                if(status == 1)
                {
                    JOptionPane.showMessageDialog(this,"Data Berhasil DItambahkan","SUKSES", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else
                {
                    JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan","GAGAL",JOptionPane.WARNING_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = tbData1.getSelectedRow();
        if (baris != -1)
        {
            String NIS = tbData1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berahsil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            txtNama.setText("");
            txtNIS.setText("");
            txtKelas.setText("");
            buttonGroup1.clearSelection();
            txtEmail.setText("");
            txtAlamat.setText("");
            lahir.setText("");
            jDateChooser1.setDate(new Date());
            

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        selectData();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if("".equals(txtNIS.getText()) || "".equals(txtNama.getText()) || "".equals(lahir.getText())||
                "".equals(lahir.getText()) || "".equals(txtKelas.getText())||
                "".equals(txtEmail.getText())||"".equals(txtAlamat.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }else
        {
            String JK = "";
            if (rdLaki.isSelected())
            {
                JK = "L";
            } else
            {
                JK = "P";
            }
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
            String tanggal = dateFormat.format(jDateChooser1.getDate());
            
            String SQL = "UPDATE t_siswa SET"
                    + "WHERE NIS='"+txtNIS.getText()+"'"
                    + "WHERE NamaSiswa='"+txtNama.getText()+"',"
                    + "WHERE Kelas='"+txtKelas.getText()+"',"
                    +"WHERE Email='"+txtEmail.getText()+"',"
                    + "WHERE JenisKelamin='"+JK+"',"
                    +"WHERE Alamat='"+txtAlamat.getText()+"',"
                    +"WHERE TempatLahir='"+lahir.getText()+"',"
                    + "WHERE TanggalLahir='"+tanggal+"'";
                    
            int status = KoneksiDB.execute(SQL);
            if(status==0)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal diupdate","sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbData1MouseClicked
        // TODO add your handling code here:
        int baris = tbData1.getSelectedRow();
        if(baris != -1)
        {
            txtNIS.setText(tbData1.getValueAt(baris, 0).toString());
            txtNama.setText(tbData1.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals(tbData1.getValueAt(baris,2).toString()))
            {   rdLaki.setSelected(true);
            }else
            {
                rdPerempuan.setSelected(true);
            }
            txtKelas.setText(tbData1.getValueAt(baris, 3).toString());
            txtEmail.setText(tbData1.getValueAt(baris, 4).toString());
            txtAlamat.setText(tbData1.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tbData1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try
        {
            tbData1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e)
        {
            System.err.format("Connot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    public void selectData()
        {
            String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat","TempatLahir","TanggalLahir"};
            DefaultTableModel dtm = new DefaultTableModel (null, kolom);
            String SQL = "SELECT * FROM t_siswa";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try{
            while(rs.next())
            {
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3)))
                {
                    JenisKelamin = "Laki-Laki";
                } else
                {
                    JenisKelamin = "Perempuan";
                }
                String  Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String TempatLahir = rs.getString(7) ;
                String TanggalLahir = rs.getString(8);
                jDateChooser1.setDate(rs.getDate("TanggalLahir"));
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat,TempatLahir,TanggalLahir};
                dtm.addRow(data);
            }
            } catch (SQLException ex)
            {
                Logger.getLogger(frmMain.class.getName()).log(Level.SERVER,null,ex);
            }
                tbData1.setModel((TableModel) dtm);

        }
    
    public void setTanggal()
    {
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
    labeltanggal.setToolTipText(kal.format(skrg));
    }
    
    public void SetJam()
    {
        ActionListener taskPerformer;
        taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEven evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <=9)
                {
                    String nol_jam = "0";
                }
                if(nilai_menit <= 9)
                {
                    String nol_menit = "0";
                }
                if(nilai_detik <= 9)
                {
                    String nol_detik = "0";
                }
                String nol_jam = null;
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String nol_menit = null;
                
                String menit = nol_menit + Integer.toString(nilai_menit);
                String nol_detik = null;
                String detik = nol_detik + Integer.toString(nilai_detik);
                
                labeljam.setText("Jam "+jam+":"+menit+":"+detik);
            }

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        new Timer(100, taskPerformer).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField lahir;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tbData1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    private static class Level {

        private static java.util.logging.Level SERVER;

        public Level() {
        }
    }

    private static class ActionEven {

        public ActionEven() {
        }
    }

    
}
